version: "3.9"

services:
  heimdall:
    restart: always
    image: linuxserver/heimdall:latest
    volumes:
      - '/opt/heimdall/config:/config'
      - '/opt/shared:/shared'
    ports:
      - "XXXX:80"
    environment:
      - PUID=1000
      - PGID=127
      - TZ='${TZ}'
   samba:
    image: dperson/samba
    container_name: samba
    restart: always
    stdin_open: true
    tty: true
    environment:
      TZ: '${TZ}'

      # advertise shares, default: true, or false (open ports 137, 138)
      NMBD: "true"

      # add a single user. If you need more, use command instead of environment
      # required arg: "<username>;<passwd>"
      # <username> for user
      # <password> for user
      # [ID] for user, default: ""
      # [group] for user, default: ""
      USER: "yourname;password"

      # set the UID for the samba share, default: ""
      USERID: "0"

      # set the GID for the samba share, default: ""
      GROUPID: "0"

      # add a single share. If you need more, use command instead of environment
      # required arg: "<name>;</path>"
      # <share_name>;
      # <path_to_share>;
      # [browsable] default:'yes' or 'no';
      # [read_only] default:'yes' or 'no';
      # [guest]: default: 'yes' or 'no';
      # [users]: default: 'all' or list of allowed users;
      # [admins] default: 'none' or list of admin users;
      # [writelist] default: 'none' or list of users that can write to read-only share;
      # [comment] default: 'none' or description of share
      SHARE: "sharename;/mnt;yes;no;no;yourname;'none';'none';'Homeserver"

      # workgroup/domain name for share default: "MYGROUP"
      WORKGROUP: "Homeserver"

      # if set, disables recycle bin for shares
      RECYCLE: ""

      # if set, disables SMB2 minimum version
      # SMB: ""

    networks:
      - default
    ports:
      - "137:137/udp" # required to advertise shares (NMBD)
      - "138:138/udp" # required to advertise shares (NMBD)
      - "139:139/tcp" # default smb port
      - "445:445/tcp" # default smb port
    read_only: false
    tmpfs:
      - /tmp
    volumes:
      - {$MOUNTDIR}:/mnt:z # :z allows share to be used by multiple containers
